### ISSUE TITLE
CPU開場對話

### ISSUE THREAD

**Issue by ASBB053** [unlightvbe/unlightvbe_qs#10]
請問，有可能追加CPU方的開場台詞嗎？
印象中，原作遊戲後期一些Quest Story活動的CPU是有開場台詞的(而且，有些還有限定台詞)。

**Comment by andyciu** [comment]
可以考慮，但我覺得這比較屬於特例所以要加的話應該是架構內另外再加類型上去
然後在此之前可能要先解決VBEPerson的拆分問題與腳本參數傳遞問題 ~~（不然直接1 to 60下去有點太high了）~~

**Comment by andyciu** [comment]
此issue已反映於Build 1655之更新，感謝回報。
