### ISSUE TITLE
CPU的傷害/恢復：資訊變數記錄異常(VBEVSStageNum階段46/48)

### ISSUE THREAD

**Issue by ASBB053** [unlightvbe/unlightvbe_qs#7]
當對手為電腦時，階段46/48無法正常紀錄VBEVSStageNum(4)/VBEVSStageNum(3)的數值。
若CPU受到直傷或骰傷/補血為1點，VBEVSStageNum(4)/VBEVSStageNum(3)的顯示為2。
若CPU受到直傷或骰傷/補血為2點，VBEVSStageNum(4)/VBEVSStageNum(3)的顯示為1。
若CPU受到直傷或骰傷/補血為3點以上，VBEVSStageNum(4/VBEVSStageNum(3)的顯示為0。

**Comment by andyciu** [comment]
此issue已修正於Build 1328之更新，感謝回報。
