### ISSUE TITLE
行動卡等相關

### ISSUE THREAD

**Issue by ASBB053** [unlightvbe/unlightvbe_qs#9]
VBEPageCardNumVS(?, 2)/(?, 4)似乎有一些問題，有時計算出來的值會跟實際不一樣(目前在劍/槍類型有發生過)。

另外，請問目前是否有辦法在每抽取一張卡片時去判定它的類別和數值呢？
嘗試利用上述的變數去實現「南瓜王・S」的四技：
【灰暗之眼】：追加抽牌。直到手牌中的劍卡數值合計達到7以上<MAX:10張>。
卻發現抽牌當下似乎沒辦法偵測到類型和數值，只能偵測到抽牌動作之前的手牌。

**Comment by andyciu** [comment]
`VBEPageCardNumVS`的狀況我再找時間看看。
抽取卡片判定的部分，我目前是有想包含此在內的一些卡牌類執行指令帶執行階段事件，配合當下受影響的卡片資訊帶引數這樣，實作應該是可行

**Comment by andyciu** [comment]
> `VBEPageCardNumVS`的狀況我再找時間看看。  

我瀏覽了一下程式碼感覺是沒啥問題，都是by pass的，如果資訊有錯的話那應該在算骰數的時候就會發現了

**Comment by andyciu** [comment]
此issue已反映於Build 1655之更新，感謝回報。
